#include <emscripten/bind.h>
#include "cmark-gfm.h"

using namespace emscripten;

EMSCRIPTEN_BINDINGS(my_constant_example) {
    constant("CMARK_OPT_DEFAULT", CMARK_OPT_DEFAULT);
    constant("CMARK_OPT_SOURCEPOS", CMARK_OPT_SOURCEPOS);
    constant("CMARK_OPT_HARDBREAKS", CMARK_OPT_HARDBREAKS);
    constant("CMARK_OPT_SAFE", CMARK_OPT_SAFE);
    constant("CMARK_OPT_UNSAFE", CMARK_OPT_UNSAFE);
    constant("CMARK_OPT_NOBREAKS", CMARK_OPT_NOBREAKS);
    constant("CMARK_OPT_NORMALIZE", CMARK_OPT_NORMALIZE);
    constant("CMARK_OPT_VALIDATE_UTF8", CMARK_OPT_VALIDATE_UTF8);
    constant("CMARK_OPT_SMART", CMARK_OPT_SMART);
    constant("CMARK_OPT_GITHUB_PRE_LANG", CMARK_OPT_GITHUB_PRE_LANG);
    constant("CMARK_OPT_LIBERAL_HTML_TAG", CMARK_OPT_LIBERAL_HTML_TAG);
    constant("CMARK_OPT_FOOTNOTES", CMARK_OPT_FOOTNOTES);
    constant("CMARK_OPT_STRIKETHROUGH_DOUBLE_TILDE", CMARK_OPT_STRIKETHROUGH_DOUBLE_TILDE);
    constant("CMARK_OPT_TABLE_PREFER_STYLE_ATTRIBUTES", CMARK_OPT_TABLE_PREFER_STYLE_ATTRIBUTES);
    constant("CMARK_OPT_FULL_INFO_STRING", CMARK_OPT_FULL_INFO_STRING);
}
